### PR TITLE
Optimize Linux package installation

### PR DESCRIPTION
**Pull request by MisterDA**
Crunch update / upgrade / install as much as possible. Clean caches.

- [ ] https://github.com/ocurrent/docker-base-images/pull/212

### CODE REVIEW

**Comment by MisterDA** [comment]
This seems to be working as expected!

**Comment by kit-ty-kate** [comment]
nope

**Comment by kit-ty-kate** [comment]
I'm reverting this. The system package manager's cache should always be present, otherwise opam depext does not work anymore.

**Comment by avsm** [comment]
Agreed. I think the old opam-depext equivalent of `opam depext -u` no longer exists in opam 2.1, which would have not encountered this problem (as it would update the package manager db before doing the querying).  It's not in 2.1 as that's too slow for the integrated depext.

**Pull request merged**
